local _, ns = ...

ns.TrainingData = {
    primaryProfessions = {
        Alchemy = true,
        Blacksmithing = true,
        Enchanting = true,
        Engineering = true,
        Herbalism = true,
        Leatherworking = true,
        Mining = true,
        Skinning = true,
        Tailoring = true,
    },

    secondarySkills = {
        ["Cooking"] = {
            learnLevel = 5,
            where = "Cooking trainers in most starting towns and capital cities.",
            costCopper = 100,
            detail = "A low-risk way to turn meat drops into useful food buffs and recovery.",
        },
        ["First Aid"] = {
            learnLevel = 5,
            where = "First Aid trainers in starting towns and capital cities.",
            costCopper = 100,
            detail = "Bandages are one of the strongest early Hardcore safety tools.",
        },
        ["Fishing"] = {
            learnLevel = 5,
            where = "Fishing trainers near water in starting areas and capital cities.",
            costCopper = 100,
            detail = "Pairs naturally with Cooking and gives safe downtime value.",
        },
    },

    professionRanks = {
        DEFAULT = {
            {
                rank = "Journeyman",
                requiredSkill = 50,
                upcomingSkill = 40,
                requiredCap = 75,
                targetCap = 150,
                where = "An appropriate profession trainer.",
                costCopper = 500,
            },
            {
                rank = "Expert",
                requiredSkill = 125,
                upcomingSkill = 115,
                requiredCap = 150,
                targetCap = 225,
                where = "An expert trainer or profession book vendor, depending on profession and faction.",
                costCopper = 5000,
            },
            {
                rank = "Artisan",
                requiredSkill = 200,
                upcomingSkill = 185,
                requiredCap = 225,
                targetCap = 300,
                where = "An artisan trainer, often outside capital cities.",
                costCopper = 50000,
            },
        },
        ["First Aid"] = {
            {
                rank = "Journeyman",
                requiredSkill = 50,
                upcomingSkill = 40,
                requiredCap = 75,
                targetCap = 150,
                where = "First Aid trainers in major cities.",
                costCopper = 500,
            },
            {
                rank = "Expert",
                requiredSkill = 125,
                upcomingSkill = 115,
                requiredCap = 150,
                targetCap = 225,
                where = "Buy Expert First Aid - Under Wraps from Deneb Walker in Stromgarde Keep or Balai Lok'Wein in Brackenwall Village.",
                costCopper = 10000,
            },
            {
                rank = "Artisan",
                requiredSkill = 225,
                upcomingSkill = 210,
                requiredCap = 225,
                requiredLevel = 35,
                targetCap = 300,
                where = "Complete Triage from Doctor Gustaf VanHowzen in Theramore or Doctor Gregory Victor in Hammerfall.",
                cost = "Quest unlock",
            },
        },
        ["Cooking"] = {
            {
                rank = "Journeyman",
                requiredSkill = 50,
                upcomingSkill = 40,
                requiredCap = 75,
                targetCap = 150,
                where = "Cooking trainers in major cities.",
                costCopper = 500,
            },
            {
                rank = "Expert",
                requiredSkill = 125,
                upcomingSkill = 115,
                requiredCap = 150,
                targetCap = 225,
                where = "Buy Expert Cookbook from Shandrina in Ashenvale or Wulan in Desolace.",
                costCopper = 10000,
            },
            {
                rank = "Artisan",
                requiredSkill = 225,
                upcomingSkill = 210,
                requiredCap = 225,
                requiredLevel = 35,
                targetCap = 300,
                where = "Complete the Clamlette Surprise cooking quest in Gadgetzan.",
                cost = "Quest unlock",
            },
        },
        ["Fishing"] = {
            {
                rank = "Journeyman",
                requiredSkill = 50,
                upcomingSkill = 40,
                requiredCap = 75,
                targetCap = 150,
                where = "Fishing trainers in major cities and fishing hubs.",
                costCopper = 500,
            },
            {
                rank = "Expert",
                requiredSkill = 125,
                upcomingSkill = 115,
                requiredCap = 150,
                targetCap = 225,
                where = "Buy Expert Fishing - The Bass and You from Old Man Heming in Booty Bay.",
                costCopper = 10000,
            },
            {
                rank = "Artisan",
                requiredSkill = 225,
                upcomingSkill = 210,
                requiredCap = 225,
                requiredLevel = 35,
                targetCap = 300,
                where = "Complete Nat Pagle, Angler Extreme in Dustwallow Marsh.",
                cost = "Quest unlock",
            },
        },
    },

    classSpells = {
        DRUID = {
            { level = 4, name = "Moonfire", rank = 1 },
            { level = 4, name = "Rejuvenation", rank = 1 },
            { level = 6, name = "Thorns", rank = 1 },
            { level = 6, name = "Wrath", rank = 2 },
            { level = 8, name = "Entangling Roots", rank = 1 },
            { level = 8, name = "Healing Touch", rank = 2 },
            { level = 10, name = "Bear Form" },
            { level = 10, name = "Demoralizing Roar", rank = 1 },
            { level = 10, name = "Maul", rank = 1 },
            { level = 10, name = "Teleport: Moonglade" },
            { level = 12, name = "Regrowth", rank = 1 },
            { level = 14, name = "Bash", rank = 1 },
            { level = 14, name = "Healing Touch", rank = 3 },
            { level = 16, name = "Aquatic Form" },
            { level = 16, name = "Swipe", rank = 1 },
            { level = 18, name = "Hibernate", rank = 1 },
            { level = 18, name = "Moonfire", rank = 3 },
            { level = 20, name = "Cat Form" },
            { level = 20, name = "Prowl", rank = 1 },
            { level = 20, name = "Starfire", rank = 1 },
        },
        HUNTER = {
            { level = 4, name = "Aspect of the Monkey" },
            { level = 4, name = "Serpent Sting", rank = 1 },
            { level = 6, name = "Arcane Shot", rank = 1 },
            { level = 6, name = "Hunter's Mark", rank = 1 },
            { level = 8, name = "Concussive Shot" },
            { level = 8, name = "Raptor Strike", rank = 2 },
            { level = 10, name = "Dismiss Pet" },
            { level = 10, name = "Revive Pet" },
            { level = 10, name = "Tame Beast" },
            { level = 12, name = "Mend Pet", rank = 1 },
            { level = 12, name = "Wing Clip", rank = 1 },
            { level = 14, name = "Eagle Eye" },
            { level = 14, name = "Scare Beast", rank = 1 },
            { level = 16, name = "Immolation Trap", rank = 1 },
            { level = 16, name = "Mongoose Bite", rank = 1 },
            { level = 18, name = "Multi-Shot", rank = 1 },
            { level = 18, name = "Track Undead" },
            { level = 20, name = "Aspect of the Cheetah" },
            { level = 20, name = "Disengage", rank = 1 },
            { level = 20, name = "Freezing Trap", rank = 1 },
        },
        MAGE = {
            { level = 4, name = "Conjure Water", rank = 1 },
            { level = 4, name = "Frostbolt", rank = 2 },
            { level = 6, name = "Conjure Food", rank = 1 },
            { level = 6, name = "Fire Blast", rank = 1 },
            { level = 6, name = "Fireball", rank = 2 },
            { level = 8, name = "Arcane Missiles", rank = 1 },
            { level = 8, name = "Polymorph", rank = 1 },
            { level = 10, name = "Conjure Water", rank = 2 },
            { level = 10, name = "Frost Nova", rank = 1 },
            { level = 12, name = "Conjure Food", rank = 2 },
            { level = 12, name = "Dampen Magic", rank = 1 },
            { level = 12, name = "Fireball", rank = 3 },
            { level = 12, name = "Slow Fall" },
            { level = 14, name = "Arcane Explosion", rank = 1 },
            { level = 14, name = "Arcane Intellect", rank = 2 },
            { level = 14, name = "Fire Blast", rank = 2 },
            { level = 14, name = "Frostbolt", rank = 4 },
            { level = 16, name = "Arcane Missiles", rank = 2 },
            { level = 16, name = "Detect Magic" },
            { level = 16, name = "Flamestrike", rank = 1 },
            { level = 18, name = "Amplify Magic", rank = 1 },
            { level = 18, name = "Fireball", rank = 4 },
            { level = 18, name = "Remove Lesser Curse" },
            { level = 20, name = "Blink" },
            { level = 20, name = "Blizzard", rank = 1 },
            { level = 20, name = "Conjure Water", rank = 3 },
            { level = 20, name = "Evocation" },
            { level = 20, name = "Fire Ward", rank = 1 },
            { level = 20, name = "Mana Shield", rank = 1 },
        },
        PALADIN = {
            { level = 4, name = "Blessing of Might", rank = 1 },
            { level = 4, name = "Judgement" },
            { level = 6, name = "Holy Light", rank = 2 },
            { level = 6, name = "Seal of the Crusader", rank = 1 },
            { level = 8, name = "Hammer of Justice", rank = 1 },
            { level = 8, name = "Purify" },
            { level = 10, name = "Lay on Hands", rank = 1 },
            { level = 10, name = "Redemption" },
            { level = 12, name = "Blessing of Protection", rank = 1 },
            { level = 12, name = "Divine Protection", rank = 1 },
            { level = 14, name = "Blessing of Wisdom", rank = 1 },
            { level = 14, name = "Seal of Righteousness", rank = 2 },
            { level = 16, name = "Righteous Fury" },
            { level = 16, name = "Sense Undead" },
            { level = 18, name = "Blessing of Freedom" },
            { level = 18, name = "Holy Light", rank = 4 },
            { level = 20, name = "Exorcism", rank = 1 },
            { level = 20, name = "Flash of Light", rank = 1 },
            { level = 20, name = "Sense Undead" },
        },
        PRIEST = {
            { level = 4, name = "Lesser Heal", rank = 2 },
            { level = 4, name = "Shadow Word: Pain", rank = 1 },
            { level = 6, name = "Power Word: Shield", rank = 1 },
            { level = 6, name = "Smite", rank = 2 },
            { level = 8, name = "Fade", rank = 1 },
            { level = 8, name = "Renew", rank = 1 },
            { level = 10, name = "Mind Blast", rank = 1 },
            { level = 10, name = "Resurrection", rank = 1 },
            { level = 10, name = "Shadow Word: Pain", rank = 2 },
            { level = 12, name = "Inner Fire", rank = 1 },
            { level = 12, name = "Power Word: Fortitude", rank = 2 },
            { level = 12, name = "Power Word: Shield", rank = 2 },
            { level = 14, name = "Psychic Scream", rank = 1 },
            { level = 14, name = "Renew", rank = 2 },
            { level = 14, name = "Smite", rank = 3 },
            { level = 16, name = "Heal", rank = 1 },
            { level = 16, name = "Mind Blast", rank = 2 },
            { level = 18, name = "Dispel Magic", rank = 1 },
            { level = 18, name = "Shadow Word: Pain", rank = 3 },
            { level = 20, name = "Flash Heal", rank = 1 },
            { level = 20, name = "Shackle Undead", rank = 1 },
        },
        ROGUE = {
            { level = 4, name = "Backstab", rank = 1 },
            { level = 4, name = "Pick Pocket" },
            { level = 4, name = "Sinister Strike", rank = 2 },
            { level = 6, name = "Gouge", rank = 1 },
            { level = 8, name = "Evasion" },
            { level = 8, name = "Eviscerate", rank = 2 },
            { level = 10, name = "Sap", rank = 1 },
            { level = 10, name = "Slice and Dice", rank = 1 },
            { level = 10, name = "Sprint", rank = 1 },
            { level = 10, name = "Stealth", rank = 1 },
            { level = 12, name = "Kick" },
            { level = 12, name = "Sinister Strike", rank = 3 },
            { level = 14, name = "Expose Armor", rank = 1 },
            { level = 14, name = "Garrote", rank = 1 },
            { level = 16, name = "Feint", rank = 1 },
            { level = 16, name = "Pick Lock" },
            { level = 18, name = "Ambush", rank = 1 },
            { level = 18, name = "Backstab", rank = 3 },
            { level = 20, name = "Distract" },
            { level = 20, name = "Poisons" },
            { level = 20, name = "Riposte" },
        },
        SHAMAN = {
            { level = 4, name = "Earth Shock", rank = 1 },
            { level = 4, name = "Stoneskin Totem", rank = 1 },
            { level = 6, name = "Earthbind Totem" },
            { level = 6, name = "Healing Wave", rank = 2 },
            { level = 8, name = "Lightning Bolt", rank = 2 },
            { level = 8, name = "Lightning Shield", rank = 1 },
            { level = 8, name = "Stoneclaw Totem", rank = 1 },
            { level = 10, name = "Flame Shock", rank = 1 },
            { level = 10, name = "Searing Totem", rank = 1 },
            { level = 10, name = "Strength of Earth Totem", rank = 1 },
            { level = 12, name = "Ancestral Spirit", rank = 1 },
            { level = 12, name = "Fire Nova Totem", rank = 1 },
            { level = 12, name = "Purge", rank = 1 },
            { level = 14, name = "Earth Shock", rank = 2 },
            { level = 14, name = "Healing Wave", rank = 3 },
            { level = 16, name = "Cure Poison" },
            { level = 16, name = "Lightning Bolt", rank = 3 },
            { level = 18, name = "Tremor Totem" },
            { level = 18, name = "Water Breathing" },
            { level = 20, name = "Ghost Wolf" },
            { level = 20, name = "Lesser Healing Wave", rank = 1 },
            { level = 20, name = "Reincarnation" },
        },
        WARLOCK = {
            { level = 4, name = "Corruption", rank = 1 },
            { level = 4, name = "Curse of Weakness", rank = 1 },
            { level = 6, name = "Life Tap", rank = 1 },
            { level = 6, name = "Shadow Bolt", rank = 2 },
            { level = 8, name = "Curse of Agony", rank = 1 },
            { level = 8, name = "Fear", rank = 1 },
            { level = 10, name = "Create Healthstone", rank = 1 },
            { level = 10, name = "Drain Soul", rank = 1 },
            { level = 10, name = "Summon Voidwalker" },
            { level = 12, name = "Health Funnel", rank = 1 },
            { level = 12, name = "Immolate", rank = 2 },
            { level = 14, name = "Curse of Recklessness", rank = 1 },
            { level = 14, name = "Drain Life", rank = 1 },
            { level = 16, name = "Life Tap", rank = 2 },
            { level = 16, name = "Unending Breath" },
            { level = 18, name = "Create Soulstone", rank = 1 },
            { level = 18, name = "Searing Pain", rank = 1 },
            { level = 20, name = "Rain of Fire", rank = 1 },
            { level = 20, name = "Ritual of Summoning" },
            { level = 20, name = "Summon Succubus" },
        },
        WARRIOR = {
            { level = 4, name = "Charge", rank = 1 },
            { level = 4, name = "Rend", rank = 1 },
            { level = 6, name = "Parry" },
            { level = 6, name = "Thunder Clap", rank = 1 },
            { level = 8, name = "Hamstring", rank = 1 },
            { level = 8, name = "Heroic Strike", rank = 2 },
            { level = 10, name = "Bloodrage" },
            { level = 10, name = "Defensive Stance" },
            { level = 10, name = "Sunder Armor", rank = 1 },
            { level = 10, name = "Taunt" },
            { level = 12, name = "Overpower", rank = 1 },
            { level = 12, name = "Revenge", rank = 1 },
            { level = 12, name = "Shield Bash", rank = 1 },
            { level = 14, name = "Demoralizing Shout", rank = 1 },
            { level = 14, name = "Rend", rank = 2 },
            { level = 16, name = "Mocking Blow", rank = 1 },
            { level = 16, name = "Shield Block" },
            { level = 18, name = "Disarm" },
            { level = 18, name = "Thunder Clap", rank = 2 },
            { level = 20, name = "Cleave", rank = 1 },
            { level = 20, name = "Retaliation" },
        },
    },
}
